import { OnInit } from '@angular/core';
import { AuthService } from "../auth.service";
import { RestService } from "../rest.service";
import { DeliveryModel } from "./delivery.model";
import { Delivery } from "./delivery";
import { FormControl } from "@angular/forms";
import { MessageService } from "../message.service";
import { MdDialog } from '@angular/material';
import { PrintService } from "../print.service";
export declare class DeliveryFormComponent implements OnInit {
    private authService;
    private restService;
    private msgService;
    dialog: MdDialog;
    private printService;
    dataIsReady: boolean;
    isWaiting: any;
    unitName: string;
    isKitchen: boolean;
    receiverName: string;
    selectedDate: Date;
    currentDate: Date;
    isToday: boolean;
    selectedIndex: number;
    receivers: any[];
    overallDeliveryModel: DeliveryModel;
    receiversSumDeliveries: any;
    receiversDeliveryModels: any;
    productName_Code: any;
    productsList: any;
    filteredNameCode: any;
    productNameCodeCtrl: FormControl;
    constructor(authService: AuthService, restService: RestService, msgService: MessageService, dialog: MdDialog, printService: PrintService);
    ngOnInit(): void;
    dateChanged(): void;
    removeDeliveryItem(item: Delivery): void;
    filterProducts(val: string): any;
    checkRealDeliveryValue(event: any, deliveryItem: Delivery): void;
    tabChanged(): void;
    updateOverallDelivery(code: string, delivery: Delivery, action: any, whichItem: any, changedValue: number): void;
    countToday(stockDate: string): boolean;
    printDelivery(deliveryModel: DeliveryModel): void;
    submitDelivery(deliveryModel: DeliveryModel): void;
    sendForPrint(deliveryModel: DeliveryModel, isAllTab: boolean): void;
    checkOverallPrintDisability(): void;
    getDeliveryData(): void;
    showProductList(): void;
    clearInput($event: any): void;
    calSumRow(rcvName: string, delivery: Delivery, operation: string): void;
    waiting(): void;
}
