import { OnInit, ElementRef } from '@angular/core';
import { BehaviorSubject } from "rxjs";
import { FormControl } from "@angular/forms";
import { ProductModel } from "./product.model";
import { RestService } from "../rest.service";
import { MessageService } from "../message.service";
export declare class ProductFormComponent implements OnInit {
    private restService;
    private messageService;
    private elementRef;
    isAdding: BehaviorSubject<boolean>;
    actionIsSuccess: BehaviorSubject<boolean>;
    productModels: ProductModel[];
    filteredProductModel: ProductModel;
    filteredNameCode: any;
    filteredName: any;
    filteredCode: any;
    isFiltered: boolean;
    productModelCtrlName: FormControl;
    productModelCtrlCode: FormControl;
    productName_Code: string[];
    productNames: string[];
    productCodes: string[];
    selectedIndex: number;
    nameChose: boolean;
    codeChose: boolean;
    autoNameInput: any;
    constructor(restService: RestService, messageService: MessageService, elementRef: ElementRef);
    ngOnInit(): void;
    private refreshProductsDropDown();
    doClickedAction(value: any): void;
    private addProduct(product);
    private deleteProduct(productId);
    private updateProduct(productId, product);
    private disableEnable(productId, btnType, isDisable);
    filterProducts(val: string, filterKind: any): any[];
    getProductName(list: any): any[];
    getProductCode(list: any): any[];
    getProduct(nameCode: string, selectorKind: any): ProductModel;
    showProductList($event: any, filterKind: any): void;
}
