import { OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { AuthService } from '../auth.service';
import { RestService } from '../rest.service';
import { InventoryModel } from './inventory.model';
import { Inventory } from './inventory';
import { Product } from '../product-form/product';
export declare class InventoryFormComponent implements OnInit {
    private authService;
    private restService;
    unopenedPack: any;
    autoNameCode: any;
    unitName: string;
    inventoryModel: InventoryModel;
    currentDate: any;
    selectedDate: any;
    isSameDates: boolean;
    submitShouldDisabled: boolean;
    products: Product[];
    productName_Code: string[];
    filteredNameCode: any;
    productNameCodeCtrl: FormControl;
    waiting: boolean;
    constructor(authService: AuthService, restService: RestService);
    ngOnInit(): void;
    filterProducts(val: string): string[];
    submitInventoryItem(inventoryItem: Inventory): void;
    submitInventories(): void;
    removeInventoryItem(inventoryItem: Inventory): void;
    disableInventoryItem(inventoryItem: Inventory): boolean;
    dateChanged(): void;
    compareDates(): void;
    isCountingDatePast(countingDate: any): boolean;
    getInventoryData(): void;
    checkDisability(item: any): void;
    showProductList(): void;
}
