import { OnInit } from '@angular/core';
import { RestService } from '../rest.service';
import { ProductModel } from '../product-form/product.model';
import { MessageService } from '../message.service';
import { UnitModel } from '../unit-form/unit.model';
export declare class ReportsComponent implements OnInit {
    private restService;
    private messageService;
    productModels: ProductModel[];
    unitModels: UnitModel[];
    branchesWithoutAllOption: any;
    branches: any[];
    branchIdForProductReport: number;
    branchIdForInventoryReport: number;
    branchIdForDeliveryReport: number;
    startDate: Date;
    endDate: Date;
    deliveryReportBtnDisabled: boolean;
    inventoryReportBtnDisabled: boolean;
    constructor(restService: RestService, messageService: MessageService);
    ngOnInit(): void;
    loadDataForProductsReport(): void;
    prepareInventoryCountingReport(): void;
    wrapInventoryCountingReportResults(rows: any): any;
    checkDisabilityStatus(): void;
    prepareDeliveryReport(): void;
    wrapDeliveryReportResults(rows: any): any;
    convertBranchProductsToCSV(products: any, branch: any): any;
    convertAllProductsToCSV(products: any): any;
    convertToCSV(keys: any, data: any): any;
    downloadCSV(data: any, filename: any): void;
}
